CREATE TABLE EMPLOYEES02
AS
SELECT  * FROM EMPLOYEES;

ALTER TABLE EMP01
ADD(JOB VARCHAR2(9));

DESC EMP01;

CREATE TABLE DOCTOR (
D_NO NUMBER(4) NOT NULL,
D_NAME VARCHAR2(20) NOT NULL,
D_SSN CHAR(14) NOT NULL,
D_EMAIL VARCHAR2(80) NOT NULL,
D_MAJOR VARCHAR2(50) NOT NULL,
T_NO NUMBER(4),
CONSTRAINT DOCTOR_D_NO_PK PRIMARY KEY(D_NO)
);

ALTER TABLE DOCTOR
ADD CONSTRAINT DOCTOR_T_NO FOREIGN KEY(T_NO) REFERENCES TREATMENT(T_NO)
ON DELETE CASCADE;

CREATE VIEW VIEW_DEPT_MAXSAL AS
SELECT D.DEPARTMENT_ID AS 부서번호,
D.DEPARTMENT_NAME AS 부서명,
MAX(E.SALARY)AS 최대급여
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME;

SELECT * FROM VIEW_DEPT_MAXSAL;