CREATE TABLE SUBJECT (
NO NUMBER NOT NULL,
S_NUM VARCHAR2(2) NOT NULL,
S_NAME VARCHAR2(80) NOT NULL,
CONSTRAINT SUBJECT_NO_PK PRIMARY KEY(NO),
CONSTRAINT SUBJECT_S_NUM_UK UNIQUE(S_NUM)
);

INSERT INTO SUBJECT(NO, S_NUM, S_NAME) VALUES (1, '01','컴퓨터학과');
INSERT INTO SUBJECT(NO, S_NUM, S_NAME) VALUES (2, '02','교육학과');
INSERT INTO SUBJECT(NO, S_NUM, S_NAME) VALUES (3, '03','신문방송학과');
INSERT INTO SUBJECT(NO, S_NUM, S_NAME) VALUES (4, '04','인터넷비즈니스과');
INSERT INTO SUBJECT(NO, S_NUM, S_NAME) VALUES (5, '05','기술경영과');

SELECT*FROM SUBJECT ORDER BY NO;

--일련번호를 쿼리문으로 구해 학과 데이터를 입력해주세요
INSERT INTO SUBJECT (NO, S_NUM, S_NAME)
VALUES ((SELECT MAX(NO) + 1 FROM SUBJECT), '06','통계학과');

--학과 테이블에 일련번호(NO)를 시퀀스에 의해 저장되도록 시퀀스 생성
CREATE SEQUENCE SUBJECT_SEQ
START WITH 7
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
NOCYCLE
CACHE 2;

INSERT INTO SUBJECT(NO, S_NUM, S_NAME) VALUES (SUBJECT_SEQ.NEXTVAL, '07','역사학과');
INSERT INTO SUBJECT(NO, S_NUM, S_NAME) VALUES (SUBJECT_SEQ.NEXTVAL, '08','인문학과');


CREATE TABLE STUDENT (
NO NUMBER NOT NULL,
SD_NUM VARCHAR2(8) NOT NULL,
SD_NAME VARCHAR2(20) NOT NULL,
SD_ID VARCHAR2(15) NOT NULL,
SD_PASSWD VARCHAR2(15) NOT NULL,
S_NUM VARCHAR2(2) NOT NULL,
SD_BIRTH CHAR(8) NOT NULL,
SD_PHONE VARCHAR2(15) NOT NULL,
SD_ADDRESS VARCHAR2(200) NOT NULL,
SD_EMAIL VARCHAR2(100) NOT NULL,
SD_DATE DATE DEFAULT SYSDATE,
CONSTRAINT STUDENT_NO_PK PRIMARY KEY (NO),
CONSTRAINT STUDENT_SD_NUM_UK UNIQUE(SD_NUM),
CONSTRAINT STUDENT_ID_UK UNIQUE(SD_ID),
CONSTRAINT STUDENT_S_NUM_FK FOREIGN KEY(S_NUM) REFERENCES SUBJECT (S_NUM)
);

INSERT INTO STUDENT (NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL,SD_DATE)
VALUES (1, '06010001', '김정수', 'JAVAJSP', '061010', '01', '20061010',' 01032567987', '서울시 서대문구 창전동', 'DFGDF@GMAIL.COM',SYSDATE);
INSERT INTO STUDENT (NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL,SD_DATE)
VALUES (2, '95010002', '김수현', 'JDBCMANIA', '951010', '01', '19950510', '01023574895', '서울시 서초구 양재동', 'FGDFNN@GMAIL.COM',SYSDATE);
INSERT INTO STUDENT (NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL,SD_DATE)
VALUES (3, '98040001', '공지영', 'GONJI', '981010', '04','19980406', '01025416788', '부산광역시 해운대구 반송동', 'FEWJJ@GMAIL.COM',SYSDATE);
INSERT INTO STUDENT (NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL,SD_DATE)
VALUES (4, '02050001', '조수영', 'WATER', '201010','05', '20000610', '01098774565', '대전광역시 중구 은행동', 'QWFGRDF@GMAIL.COM',SYSDATE);
INSERT INTO STUDENT (NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL,SD_DATE)
VALUES (5, '94040002', '최경란', 'NOVEL', '941010', '04', '20020421', '01014789545', '수원시 장안구 이목동', 'LGLHGASDF@GMAIL.COM',SYSDATE);
INSERT INTO STUDENT (NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL,SD_DATE)
VALUES (6, '08020001', '안익태', 'KOREA', '801010', '02','20000701', '01066895456', '서울 강남', 'QWERASDF@GMAIL.COM',SYSDATE);

CREATE SEQUENCE STUDENT_SEQ
START WITH 7
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
NOCYCLE
CACHE 2;

SELECT*FROM STUDENT ORDER BY NO;

INSERT INTO STUDENT (NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL,SD_DATE)
VALUES (STUDENT_SEQ.NEXTVAL, '00020001', '김요한', 'AGAPE', '900716', '02','19900701', '01078895456', '서울 강남', 'AGAPE@GMAIL.COM',SYSDATE);



CREATE TABLE LESSON (
NO NUMBER NOT NULL,
L_ABBRE VARCHAR2(2) NOT NULL,
L_NAME VARCHAR2(80) NOT NULL,
CONSTRAINT LESSON_NO_PK PRIMARY KEY(NO),
CONSTRAINT LESSON_L_ABBRE_UK UNIQUE(L_ABBRE)
);

INSERT INTO LESSON(NO, L_ABBRE, L_NAME) VALUES(1,'K','국어');
INSERT INTO LESSON(NO, L_ABBRE, L_NAME) VALUES(2,'M','수학');
INSERT INTO LESSON(NO, L_ABBRE, L_NAME) VALUES(3,'E','영어');
INSERT INTO LESSON(NO, L_ABBRE, L_NAME) VALUES(4,'H','역사');
INSERT INTO LESSON(NO, L_ABBRE, L_NAME) VALUES(5,'P','프로그래밍');
INSERT INTO LESSON(NO, L_ABBRE, L_NAME) VALUES(6,'D','데이터베이스');
INSERT INTO LESSON(NO, L_ABBRE, L_NAME) VALUES(7,'ED','교육학이론');

CREATE SEQUENCE LESSON_SEQ
START WITH 8
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
NOCYCLE
CACHE 2;

SELECT*FROM LESSON;

INSERT INTO LESSON(NO, L_ABBRE, L_NAME) VALUES(LESSON_SEQ.NEXTVAL,'PS','물리학과');
--수강테이블
CREATE TABLE TRAINEE(
NO NUMBER NOT NULL,
SD_NUM VARCHAR2(8) NOT NULL,
L_ABBRE VARCHAR2(2) NOT NULL,
T_SECTION VARCHAR2(50) NOT NULL,
T_DATE DATE DEFAULT SYSDATE,
CONSTRAINT TRAINEE_NO_PK PRIMARY KEY(NO),
CONSTRAINT TRAINEE_SD_NUM_FK FOREIGN KEY(SD_NUM) REFERENCES STUDENT(SD_NUM),
CONSTRAINT TRAINEE_L_ABBRE_FK FOREIGN KEY(L_ABBRE) REFERENCES LESSON(L_ABBRE)
);

INSERT INTO TRAINEE
VALUES ( 1, '06010001','P','MAJOR',SYSDATE);
INSERT INTO TRAINEE
VALUES ( 2, '95010002','E','CULTURE',SYSDATE);
INSERT INTO TRAINEE
VALUES ( 3, '98040001','D','MAJOR',SYSDATE);
INSERT INTO TRAINEE
VALUES ( 4, '02050001','M','MINOR',SYSDATE);
INSERT INTO TRAINEE
VALUES ( 5, '94040002','P','MAJOR',SYSDATE);
INSERT INTO TRAINEE
VALUES ( 6, '08020001','ED','MAJOR',SYSDATE);

CREATE SEQUENCE TRAINEE_SEQ
START WITH 7
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
NOCYCLE
CACHE 2;


SELECT*FROM TRAINEE;

INSERT INTO TRAINEE
VALUES ( TRAINEE_SEQ.NEXTVAL, '08020001','ED','MAJOR',SYSDATE);

