CREATE TABLE LESSON (
NO NUMBER NOT NULL,
L_ABBRE VARCHAR2(2) NOT NULL,
L_NAME VARCHAR2(80) NOT NULL,
CONSTRAINT LESSON_NO_PK PRIMARY KEY(NO),
CONSTRAINT LESSON_L_ABBRE_UK UNIQUE(L_ABBRE)
);

INSERT INTO LESSON (NO, L_ABBRE, L_NAME )VALUES(1,'K','국어');
INSERT INTO LESSON (NO, L_ABBRE, L_NAME )VALUES(2,'M','수학');
INSERT INTO LESSON (NO, L_ABBRE, L_NAME )VALUES(3,'E','영어');
INSERT INTO LESSON (NO, L_ABBRE, L_NAME )VALUES(4,'H','역사');
INSERT INTO LESSON (NO, L_ABBRE, L_NAME )VALUES(5,'P','프로그래밍');
INSERT INTO LESSON (NO, L_ABBRE, L_NAME )VALUES(6,'D','데이터베이스');
INSERT INTO LESSON (NO, L_ABBRE, L_NAME )VALUES(7,'ED','교육학이론');

CREATE TABLE TRAINEE (
NO NUMBER NOT NULL,
SD_NUM VARCHAR2(8) NOT NULL,
L_ABBRE VARCHAR2(2) NOT NULL,
T_SECTION VARCHAR2(50) NOT NULL,
T_DATE DATE DEFAULT SYSDATE,
CONSTRAINT TRAINEE_NO_PK PRIMARY KEY(NO),
CONSTRAINT TRAINEE_SD_NUM_FK_ FOREIGN KEY(SD_NUM) REFERENCES STUDENT(SD_NUM),
CONSTRAINT TRAINEE_L_ABBRE_FK FOREIGN KEY (L_ABBRE) REFERENCES LESSON(L_ABBRE)
);

INSERT INTO TRAINEE
VALUES(1, '06010001','P','MAJOR',SYSDATE);

INSERT INTO TRAINEE
VALUES(1, '06010001','P','MAJOR',SYSDATE);

INSERT INTO TRAINEE
VALUES(1, '06010001','P','MAJOR',SYSDATE);

INSERT INTO TRAINEE
VALUES(1, '06010001','P','MAJOR',SYSDATE);

INSERT INTO TRAINEE
VALUES(1, '06010001','P','MAJOR',SYSDATE);

INSERT INTO TRAINEE
VALUES(1, '06010001','P','MAJOR',SYSDATE);