--PL/SQL 총사원의 수와 급여의 합, 급여의 평균을 변수에 대입하여 출력하여 보자
DECLARE
COUNT_EMPLOYEE NUMBER;
SUM_SALARY NUMBER;
AVG_SALARY NUMBER;

BEGIN
SELECT COUNT(*) INTO COUNT_EMPLOYEE
FROM EMPLOYEES;

SELECT SUM(SALARY) INTO SUM_SALARY 
FROM EMPLOYEES;

SELECT AVG(SALARY) INTO AVG_SALARY
FROM EMPLOYEES;

DBMS_OUTPUT.PUT_LINE('총사원' || COUNT_EMPLOYEE);
DBMS_OUTPUT.PUT_LINE('총급여' || SUM_SALARY);
DBMS_OUTPUT.PUT_LINE('평균 급여' || AVG_SALARY);
END;
/

DECLARE
VDEPARTMENT DEPARTMENTS%ROWTYPE;
CURSOR C1
IS
SELECT * FROM DEPARTMENTS;
BEGIN
DBMS_OUTPUT.PUT_LINE('부서번호/부서명/지역명');
DBMS_OUTPUT.PUT_LINE('-------------------');
FOR VDEPARTMENTS IN C1 LOOP
DBMS_OUTPUT.PUT_LINE(VDEPARTMENTS.DEPARTMENT_ID||''||
RPAD(VDEPARTMENTS.DEPARTMENT_NAME,20)||''||VDEPARTMENTS.LOCATION_ID);
END LOOP;
END;
/

DECLARE
VRANDOMID EMPLOYEES.DEPARTMENT_ID%TYPE;--임의의 부서번호
VSALARYSTRING VARCHAR2(20); --급여등급
