SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD'), TO_CHAR(SYSDATE, 'DL')
FROM DUAL;

SELECT TO_CHAR(HIRE_DATE, 'YYYY/MM/DD/DAY')
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

SELECT TO_CHAR (HIRE_DATE, 'YYYY"년"MM"월"DD"일"DAY') AS HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

--그룹 함수의 종류
--SUM 그룹의 누적합계를 반환한다
--AVG 그룹의 평균을 반환한다
--MAX 그룹의 최댓값을 반환한다
--MIN 그룹의 최솟값을 반환한다
--COUNT 그룹의 총 개수를 반환한다

--직원의 총 급여 구하기 
SELECT SUM(SALARY)
FROM EMPLOYEES;
SELECT TO_CHAR(SUM(SALARY),'$999,999')AS TOTAL
FROM EMPLOYEES;

SELECT AVG(SALARY)
FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY),1)
FROM EMPLOYEES;

