CREATE TABLE TB_USER(
USER_NO NUMBER PRIMARY KEY,
USER_ID VARCHAR2(50) UNIQUE NOT NULL,
USER_NAME VARCHAR2(50) NOT NULL,
USER_AGE NUMBER NOT NULL
);
CREATE SEQUENCE SEQ_UNO
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'gd_hong','È«±æµ¿', 20);
INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'sh_han','ÇÑ¼ÒÈñ', 28);
INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'jm_park','Áö¹Î', 27);
COMMIT;

SELECT*FROM TB_USER;

CREATE TABLE MEMBER (
USER_NO NUMBER PRIMARY KEY,
USER_ID VARCHAR2(20) NOT NULL,
USER_PW VARCHAR2(20) NOT NULL,
USER_NAME VARCHAR2(20) NOT NULL,
USER_ADDR VARCHAR2(50) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_MEMBER;

SELECT * FROM MEMBER;



